---
title: "Are PECs Correlated"
format: html
editor: visual
---

## Jannicke's Email

Regarding the question of whether PEC1, PEC2, \..., PEC6 are independent (for the 6 APIs).

Would it be possible for you to run a statistical test to check this? I think you can use a set of linear regressions where each PEC (values for the 20 years) is either x or y. Then the significance level alpha (0.05) must be reduced to account for the total no. of tests (all combinations), for example by Bonferroni correction.

```{r}
# Starting with sales weights
API_sales_weights_1999_2018

# How do we make all combinations?
API_combinations <- expand.grid(analysed_APIs, analysed_APIs) |> 
    filter(Var1 != Var2) |> 
    transmute(API1 = as.character(Var1),
              API2 = as.character(Var2))

# Remove duplicates
API_combinations <- API_combinations[!duplicated(apply(API_combinations, 1, function(x) paste(sort(x), collapse = ""))), ] |> 
    tibble()
    
# Join the tibble of all possible pairs with sales weights for both APIs
API_combination_sales_weights <- left_join(API_combinations, 
                  API_sales_weights_1999_2018 |> select(-InChIKey_string),
                  by = c("API1" = "API_Name"), 
                  relationship = "many-to-many") |> 
    rename(Total_Sold_kg_API1 = Total_Sold_kg) |> 
    left_join(API_sales_weights_1999_2018 |> select(-InChIKey_string), 
              by = c("API2" = "API_Name", "Year" = "Year"), 
              relationship = "many-to-many") |> 
    rename(Total_Sold_kg_API2 = Total_Sold_kg)

API_combination_sales_weights_LM <- tibble()

# Maybe it's much easier than I thought?
pairwise.t.test(x = API_sales_weights_1999_2018$Total_Sold_kg, 
                g = API_sales_weights_1999_2018$API_Name,
                p.adjust.method = "bonferroni",
                pool.sd	= FALSE)

```

If none of the PEC combinations have a significant correlation (p below the adjusted limit), then we can say that they are at least not correlated.

The same exercise could be done with three different response variables (separately): Sales total, sales per capita, and PEC.

There may be some better method for doing all the possible regressions at once, but not from the top of my head.

If some of the, say, PECs are correlated, then we can discuss whether they are still conditionally independent. I've been reading up on conditional independence and I think we can say that e.g. PEC1 is independent of PEC2 given the sales year. That is, if you do know the sales year (or if you run the BN for a given scenario year), then information on PEC1 will not give you any additional information or better prediction of PEC2. Even if both PEC1 and PEC2 increase with sales year (a correlation caused by increased population size and drugs use).

The aim of this exercise is to decide if it's ok to use the joint probability expression the way we have done. 

From what I understand, events A and B can be (marginally) dependent but still conditionally independent, or vise versa. It depends on the conditions given and the context and how you frame the question.

In our case, If all PECs are uncorrelated (no statisticslly significant correlations), then I'd say it's anyway ok to use the joint probability expression.

If some PECs are correlated, but we agree that they are still conditionally independent (conditional on the sales year), then I believe it's still ok. Since our joint probability calculation is meant to apply for a given year. 

But these are issues that I'd like us to discuss more with Anders at some point. 

If you still consider including the joint probability calculation in your paper, then 

I can try to make time for a meeting after 17 July if you set it up (with or without Anders), or you can have a meeting just with him if that works better. 

If this will instead go into a separate paper, then it might as well wait.

Whether the PNECs are still valid for similarly acting substances (Merete's objections) is another issue, which I still think we should handle with a MAF-like adjustment of the PNECs. The PNEC is already such a dodgy concept, it doesn't matter if we mess it up further. But the PECs still have a meaningful interpretation and should not be converted into TUs (which are not very meaningful, in my view).

Some links with good examples on conditional independence:

<https://math.stackexchange.com/questions/23093/could-someone-explain-conditional-independence>

<https://towardsdatascience.com/conditional-independence-the-backbone-of-bayesian-networks-85710f1b35b>
